version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: $PRISMA_MANAGEMENT_API_SECRET
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: $DB_USER
            password: $DB_PASSWORD
# Setup for Amazon RDS MySQL instance (host, user, PW in .env)
# SSL does not work because there is no way to verify the certificate
#            host: $PRISMA_DB_HOST
#            port: 3306
#            database: raincheckdbmysql
#            user: $PRISMA_DB_USER
#            password: $PRISMA_DB_PASSWORD
#            ssl: false

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: ~
