version: '3.5'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    networks:
      - webapp
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: $PRISMA_MANAGEMENT_API_SECRET
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: $DB_USER
            password: $DB_PASSWORD
            connectionLimit: 10
  mysql:
    image: mysql:5.7
    restart: always
    networks:
      - webapp
      - notify
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    volumes:
      - mysql:/var/lib/mysql
  backend:
    image: flodocks/raincheck-db:latest
    ports:
      - '4000:4000'
    networks:
      - webapp
    environment:
      APP_SECRET: $APP_SECRET
      HERE_API_KEY: $HERE_API_KEY
      FRONTEND_URI: $FRONTEND_URI
      PRISMA_ENDPOINT: http://prisma:4466
volumes:
  mysql: ~
networks:
  webapp:
    name: "raincheck-webapp"
    driver: "bridge"
  notify:
    name: "raincheck-notify"
    driver: "bridge"
